# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
- task: VSTest@3
  inputs:
    testSelector: 'testPlan'
    testPlan: '1'
    testSuite: '2'
    testConfiguration: '1'
    searchFolder: '$(System.DefaultWorkingDirectory)'
    testRunTitle: 'Test_run1'
trigger:
- main

pool:
  name: 'default'
  vmImage: 'Test_agent_18March'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
